version: "3.8"
services:
  workspace:
    container_name: yearn-devcontainer
    build:
      context: .
      dockerfile: Dockerfile

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"

    # Pass environment variables
    env_file:
      - ./devcontainer.env

    # Create or bind volumes between host and remote
    volumes:
      # Use a named volume for the source code
      - ..:/root/yearn-exporter

      # Create volume so remote can run Host's Docker
      - /var/run/docker.sock:/var/run/docker.sock

      # Bind host's credentials
      - type: bind
        source: ${HOME}${USERPROFILE}/.ssh
        target: /root/.ssh

      - type: bind
        source: ${HOME}${USERPROFILE}/.pyenv/versions
        target: /root/.pyenv/versions

      - type: bind
        source: ${HOME}${USERPROFILE}/.aws
        target: /root/.aws

      - type: bind
        source: ${HOME}${USERPROFILE}/.gitconfig-ledger
        target: /root/.gitconfig-ledger

      - type: bind
        source: ${HOME}${USERPROFILE}/.gitconfig-gbto
        target: /root/.gitconfig-gbto

    network_mode: service:db

  db:
      image: postgres:latest
      restart: unless-stopped
      volumes:
        - postgres-data:/var/lib/postgresql/data
        - run-postgresql:/var/run/postgresql
      environment:
        POSTGRES_USER: postgres
        POSTGRES_DB: postgres
        POSTGRES_PASSWORD:

volumes:
  postgres-data:
  run-postgresql:
